### PR TITLE
SELSA aggr support for 0 proposal

### PR DESCRIPTION
**Pull request by Chop1**
see #370

### CODE REVIEW

**Comment by GT9505** [comment]
Hi~, thanks for your contribution. Could you fix the lint error firstly by following [Contributing](https://github.com/open-mmlab/mmtracking#contributing)?

**Comment by Chop1** [comment]
I will make sure to do that in a few weeks.

**Comment by zhangy0210** [comment]
按照这个页面
https://codecov.io/gh/open-mmlab/mmtracking/pull/375/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-mmlab#diff-bW10cmFjay9tb2RlbHMvYWdncmVnYXRvcnMvc2Vsc2FfYWdncmVnYXRvci5weQ==
修改了文件mmtracking/mmtrack/models/aggregators/selsa_aggregator.py文件中的class SelsaAggregator的forward函数

之后,可以顺利训练并验证selsa_faster_rcnn_r50_dc5_1x_imagenetvid.py
但运行selsa_troialign_faster_rcnn_r50_dc5_7e_imagenetvid.py依旧出现错误

**Comment by Chop1** [comment]
> 按照这个页面 https://codecov.io/gh/open-mmlab/mmtracking/pull/375/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=open-mmlab#diff-bW10cmFjay9tb2RlbHMvYWdncmVnYXRvcnMvc2Vsc2FfYWdncmVnYXRvci5weQ== 修改了文件mmtracking/mmtrack/models/aggregators/selsa_aggregator.py文件中的class SelsaAggregator的forward函数
> 
> 之后,可以顺利训练并验证selsa_faster_rcnn_r50_dc5_1x_imagenetvid.py 但运行selsa_troialign_faster_rcnn_r50_dc5_7e_imagenetvid.py依旧出现错误

(I used google traduction)
I assume you refer to  #387. In my case, these modifications resolved the issue. Do you obtain the same error as in  #387 ?
Are you using those data ? https://bvisionweb1.cs.unc.edu/ILSVRC2017/download-videos-1p39.php
I'm still planning to pass the PR next month.

**Comment by JingweiZhang12** [comment]
@Chop1  Thanks for your proposal. Would you like to continue to complete this PR?

**Comment by Chop1** [comment]
Hey, working on it right now sorry for the delay

**Pull request closed without merging**
