### PR TITLE
[Fix] fix cocoapi in parser 

### PR DESCRIPTION
**Pull request by stacezhou**
* [Fix] fix cocoapi in parser as what mmdetection have done [#4399](https://github.com/open-mmlab/mmdetection/pull/4939)
* fix a bug

### CODE REVIEW

**Comment by GT9505** [comment]
Hi~, can you fix the lint error firstly?
Besides, we don't need copy the `COCO` class from mmdet. We can directly import it (`from mmdet.datasets.api_wrappers import COCO`).

**Comment by GT9505** [comment]
Please also modify the `mmpycocotools` to `pycocotools` in `requirements/runtime.txt`, just like [#4399](https://github.com/open-mmlab/mmdetection/pull/4939) did.

**Comment by GT9505** [comment]
fixed in #259

**Comment by OpenMMLab-Coodinator** [comment]
Hi @stacezhou  ！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) , where you can share your experiences, ideas, and build connections with like-minded peers. 

To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request closed without merging**
